name: 'Marlon Lynn Architect, PA'
favicon: null
layout_spectrum: 0.57357
typography_spectrum: 0.89865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee3b24'
    - '#010101'
    - '#505050'
    - '#bfbfbf'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
