name: 'Marlon Lynn Architect, PA'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee3c24'
    - '#ffffff'
    - '#000000'
    - '#9c2717'
    - '#f7a59a'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.32914224546402693
purpose: []
